my_set = set([1,2,3,4,5])
print(my_set)
print(type(my_set))
print("-----------------------")
other_set = {6,7,8,9,10}
print(other_set)
print(type(other_set))
#los set no aceptan asignacion de datos
print("-----------------------")
print(len(my_set))
print("-----------------------")
print(2 in my_set)
print("-----------------------")
print(my_set.union(other_set))
print("-----------------------")
my_set.add(8)
print(my_set)
print("-----------------------")
my_set.remove(2)
print(my_set)
print("-----------------------")
my_set.discard(6)
print(my_set)
print("-----------------------")
my_set.pop() #elimina un dato aleatorio
print(my_set)
